"""
FastAPI application for credit risk scoring.
Requires artifacts in models/ (generated by save_artifacts.py).
"""
import sys, json
sys.path.insert(0, '.')

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

from src.feature_engineering import create_interaction_features

# ── Load artifacts at startup ─────────────────────────────────────────────────
MODEL            = joblib.load("models/model.joblib")
IMPUTER          = joblib.load("models/imputer.joblib")
RAW_FEATURES     = json.load(open("models/raw_feature_names.json"))

# Profit-optimal threshold — update this after running notebook 04
THRESHOLD = 0.35

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Credit Risk Scoring API",
    description=(
        "Predicts probability of loan default using credit bureau data. "
        "Decision threshold is profit-optimised (loss=$500/default, profit=$100/good)."
    ),
    version="1.0",
)


# ── Request / Response schemas ────────────────────────────────────────────────
class ApplicantInput(BaseModel):
    # Derogatory / adverse history
    DerogCnt:       Optional[float] = Field(None, description="Number of derogatory records")
    CollectCnt:     Optional[float] = Field(None, description="Number of collection records")
    BanruptcyInd:   Optional[float] = Field(None, description="Bankruptcy indicator (0/1)")
    TLBadDerogCnt:  Optional[float] = Field(None, description="Bad/derogatory tradeline count")
    TLBadCnt24:     Optional[float] = Field(None, description="Bad tradelines in 24 months")

    # Inquiries
    InqCnt06:        Optional[float] = Field(None, description="Inquiries in last 6 months")
    InqTimeLast:     Optional[float] = Field(None, description="Months since last inquiry")
    InqFinanceCnt24: Optional[float] = Field(None, description="Finance inquiries in 24 months")

    # Tradeline counts
    TLCnt03:  Optional[float] = Field(None, description="Tradelines opened in last 3 months")
    TLCnt12:  Optional[float] = Field(None, description="Tradelines opened in last 12 months")
    TLCnt24:  Optional[float] = Field(None, description="Tradelines opened in last 24 months")
    TLCnt:    Optional[float] = Field(None, description="Total tradeline count")
    TLSatCnt: Optional[float] = Field(None, description="Satisfactory tradeline count")

    # Balances & utilisation
    TLSum:       Optional[float] = Field(None, description="Sum of all tradeline balances")
    TLMaxSum:    Optional[float] = Field(None, description="Maximum single tradeline balance")
    TL75UtilCnt: Optional[float] = Field(None, description="Tradelines with >75% utilisation")
    TL50UtilCnt: Optional[float] = Field(None, description="Tradelines with >50% utilisation")
    TLBalHCPct:  Optional[float] = Field(None, description="Balance to high-credit ratio")

    # Delinquency
    TLDel60Cnt:     Optional[float] = Field(None, description="Tradelines 60+ days delinquent")
    TLDel3060Cnt24: Optional[float] = Field(None, description="30-60 day delinquencies in 24 months")
    TLDel90Cnt24:   Optional[float] = Field(None, description="90+ day delinquencies in 24 months")
    TLDel60CntAll:  Optional[float] = Field(None, description="Total 60-day delinquencies ever")
    TLDel60Cnt24:   Optional[float] = Field(None, description="60-day delinquencies in 24 months")

    # Credit history & account status
    TLTimeFirst:  Optional[float] = Field(None, description="Months since first tradeline opened")
    TLTimeLast:   Optional[float] = Field(None, description="Months since most recent tradeline")
    TLSatPct:     Optional[float] = Field(None, description="Percent of tradelines satisfactory")
    TLOpenPct:    Optional[float] = Field(None, description="Percent of tradelines currently open")
    TLOpen24Pct:  Optional[float] = Field(None, description="Percent of tradelines opened in 24 months")

    class Config:
        json_schema_extra = {
            "example": {
                "DerogCnt": 0,
                "CollectCnt": 0,
                "BanruptcyInd": 0,
                "InqCnt06": 1,
                "InqTimeLast": 3,
                "InqFinanceCnt24": 2,
                "TLTimeFirst": 120,
                "TLTimeLast": 6,
                "TLCnt03": 0,
                "TLCnt12": 1,
                "TLCnt24": 2,
                "TLCnt": 8,
                "TLSum": 15000,
                "TLMaxSum": 8000,
                "TLSatCnt": 7,
                "TLSatPct": 0.875,
                "TLDel60Cnt": 0,
                "TLBadDerogCnt": 0,
                "TLBadCnt24": 0,
                "TLDel3060Cnt24": 0,
                "TLDel90Cnt24": 0,
                "TLDel60CntAll": 0,
                "TLDel60Cnt24": 0,
                "TLOpenPct": 0.75,
                "TLOpen24Pct": 0.25,
                "TL75UtilCnt": 1,
                "TL50UtilCnt": 2,
                "TLBalHCPct": 0.45
            }
        }


class PredictionResponse(BaseModel):
    default_probability: float = Field(..., description="P(default), range 0-1")
    decision:            str   = Field(..., description="APPROVE or REJECT")
    risk_category:       str   = Field(..., description="LOW / MEDIUM / HIGH")


# ── Endpoints ─────────────────────────────────────────────────────────────────
@app.get("/", tags=["status"])
def root():
    return {"status": "ok", "model": "Credit Risk Scorer v1.0",
            "docs": "/docs"}


@app.get("/health", tags=["status"])
def health():
    return {"status": "healthy"}


@app.post("/predict", response_model=PredictionResponse, tags=["scoring"])
def predict(applicant: ApplicantInput):
    try:
        # Build DataFrame in the exact column order the imputer was fitted on
        data = {feat: [getattr(applicant, feat, None)] for feat in RAW_FEATURES}
        df = pd.DataFrame(data)

        # Impute missing values (median, fitted on training set)
        df_imp = pd.DataFrame(
            IMPUTER.transform(df),
            columns=df.columns,
        )

        # Add 6 hand-crafted interaction features
        df_full = create_interaction_features(df_imp)

        # Predict
        prob = float(MODEL.predict_proba(df_full)[0][1])

        decision = "REJECT" if prob >= THRESHOLD else "APPROVE"

        if prob < 0.15:
            risk_category = "LOW"
        elif prob < 0.35:
            risk_category = "MEDIUM"
        else:
            risk_category = "HIGH"

        return PredictionResponse(
            default_probability=round(prob, 4),
            decision=decision,
            risk_category=risk_category,
        )

    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))
